//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymaCord.TryOnMirror.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public Brand()
        {
            this.Glasses = new HashSet<Glass>();
            this.Hairstyles = new HashSet<Hairstyle>();
            this.ItemCategories = new HashSet<ItemCategory>();
        }
    
        public int BrandId { get; set; }
        public string BrandName { get; set; }
        public string LogoFileName { get; set; }
        public string Url { get; set; }
        public System.DateTime DateCreated { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual ICollection<Glass> Glasses { get; set; }
        public virtual ICollection<Hairstyle> Hairstyles { get; set; }
        public virtual ICollection<ItemCategory> ItemCategories { get; set; }
    }
}
