//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymaCord.TryOnMirror.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HairstyleBooking
    {
        public HairstyleBooking()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int BookingId { get; set; }
        public int UserId { get; set; }
        public int SalonId { get; set; }
        public string HairstyleFileName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ImageFileName { get; set; }
        public System.DateTime BookingDate { get; set; }
        public byte[] TimeStamp { get; set; }
        public string PhotoFileName { get; set; }
        public string Note { get; set; }
        public bool Viewed { get; set; }
        public System.Guid Identifier { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> CancelledByUserId { get; set; }
    
        public virtual Salon Salon { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual BookingStatus BookingStatus { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
