//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymaCord.TryOnMirror.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TryOnMirrorEntities : DbContext
    {
        public TryOnMirrorEntities()
            : base("name=TryOnMirrorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CalibratedHair> CalibratedHairs { get; set; }
        public DbSet<HairCategory> HairCategories { get; set; }
        public DbSet<OAuthMembership> OAuthMemberships { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<Membership> Memberships { get; set; }
        public DbSet<TracedPhoto> TracedPhotos { get; set; }
        public DbSet<Hairstyle> Hairstyles { get; set; }
        public DbSet<ContactLens> ContactLenses { get; set; }
        public DbSet<GlassCategory> GlassCategories { get; set; }
        public DbSet<Glass> Glasses { get; set; }
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Salon> Salons { get; set; }
        public DbSet<HairstyleBooking> HairstyleBookings { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<CommentType> CommentTypes { get; set; }
        public DbSet<BookingStatus> BookingStatuses { get; set; }
        public DbSet<SharedMakeover> SharedMakeovers { get; set; }
        public DbSet<HairColor> HairColors { get; set; }
        public DbSet<Brand> Brands { get; set; }
        public DbSet<ItemCategory> ItemCategories { get; set; }
    }
}
