//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymaCord.TryOnMirror.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.OAuthMemberships = new HashSet<OAuthMembership>();
            this.Roles = new HashSet<Role>();
            this.TracedPhotos = new HashSet<TracedPhoto>();
            this.Hairstyles = new HashSet<Hairstyle>();
            this.ContactLenses = new HashSet<ContactLens>();
            this.Glasses = new HashSet<Glass>();
            this.Addresses = new HashSet<Address>();
            this.Salons = new HashSet<Salon>();
            this.HairstyleBookings = new HashSet<HairstyleBooking>();
            this.Comments = new HashSet<Comment>();
            this.HairstyleBookings1 = new HashSet<HairstyleBooking>();
        }
    
        public int UserId { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
    
        public virtual ICollection<OAuthMembership> OAuthMemberships { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual Membership Membership { get; set; }
        public virtual ICollection<TracedPhoto> TracedPhotos { get; set; }
        public virtual ICollection<Hairstyle> Hairstyles { get; set; }
        public virtual ICollection<ContactLens> ContactLenses { get; set; }
        public virtual ICollection<Glass> Glasses { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Salon> Salons { get; set; }
        public virtual ICollection<HairstyleBooking> HairstyleBookings { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<HairstyleBooking> HairstyleBookings1 { get; set; }
    }
}
