//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymaCord.TryOnMirror.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingStatus
    {
        public BookingStatus()
        {
            this.HairstyleBookings = new HashSet<HairstyleBooking>();
        }
    
        public int StatusId { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<HairstyleBooking> HairstyleBookings { get; set; }
    }
}
