//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymaCord.TryOnMirror.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalibratedHair
    {
        public CalibratedHair()
        {
            this.HairCategories = new HashSet<HairCategory>();
        }
    
        public int CalibrateId { get; set; }
        public int HairWidthDifference { get; set; }
        public int HairHeightDifference { get; set; }
        public int FaceX { get; set; }
        public int FaceY { get; set; }
        public System.Guid ImageFileNameGuid { get; set; }
        public string ImageFileMimeType { get; set; }
        public string Extension { get; set; }
        public System.DateTime DateCreated { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual ICollection<HairCategory> HairCategories { get; set; }
    }
}
