//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymaCord.TryOnMirror.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.HairstyleBookings = new HashSet<HairstyleBooking>();
        }
    
        public int CommentId { get; set; }
        public string Message { get; set; }
        public int UserId { get; set; }
        public int CommentTypeId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual CommentType CommentType { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<HairstyleBooking> HairstyleBookings { get; set; }
    }
}
