//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymaCord.TryOnMirror.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharedMakeover
    {
        public long SharedId { get; set; }
        public string UrlCode { get; set; }
        public string FileName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Provider { get; set; }
    }
}
